export const IMAGES = {
  logo: '/logo.png',
  hero: '/images/hero/hero-bg.jpg',
  aboutHero: '/images/about/company-overview.jpg',
  workshop: '/images/about/workshop.jpg',
  team: '/images/about/team.jpg',
  office: '/images/about/office.jpg',
  service01: '/images/services/01-hydraulic-station.jpg',
  service02: '/images/services/02-electro-hydraulic.jpg',
  service03: '/images/services/03-robot-integration.jpg',
  service04: '/images/services/04-automation.jpg',
  service05: '/images/services/05-iot-monitor.jpg',
  service06: '/images/services/06-maintenance.jpg',
  case01: '/images/cases/01-automotive-assembly.jpg',
  case02: '/images/cases/02-hydraulic-press.jpg',
  case03: '/images/cases/03-injection-molding.jpg',
  case04: '/images/cases/04-food-packaging.jpg',
  case05: '/images/cases/05-material-handling.jpg',
  case06: '/images/cases/06-machine-tool.jpg',
  productVfd: '/images/products/vfd/MD290通用性变频器.png',
  productServo: '/images/products/servo/SV630经济型伺服驱动器.png',
  productMotor: '/images/products/motor/MS1系列低压伺服电机.png',
  productPlc: '/images/products/plc/AM500系列标准型中型PLC.png',
  productHmi: '/images/products/hmi/ITS7000 系列标准型 HMI.PNG',
  productPneumatic: '/images/products/pneumatic/CBA系列双轴气缸.png',
  productRobot: '/images/products/robot/IR-S3系列SCARA 机器人.PNG',
};

export default IMAGES;